name: CI

on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal --target wasm32-unknown-unknown
      - uses: extractions/setup-just@v1
      - uses: Swatinem/rust-cache@v2
      - run: just ci
